---
title: "250329_CrypticPSIfill"
author: "Irika Sinha"
date: "2025-02-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The purpose of this script is to take the file with manually identified cryptic exon coordinates and use those coordinates to identify left and right junction PSIs in the different conditions for i3N. 

## Packages

```{r packages}
CRANpackages <- c("tidyverse", "ggplot2", "ggpubr", "ggstats","BiocManager","viridis")
biocPackages <- c("clusterProfiler","org.Hs.eg.db")

for(i in CRANpackages){
  if(!(i %in% rownames(installed.packages()))){
    install.packages(pkgs = i)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

for(i in biocPackages){
  if(!(i %in% rownames(installed.packages()))){
    BiocManager::install(pkgs = i, ask = F)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

rm(CRANpackages,biocPackages)


```


# KEGG pathway overlap of cryptic exon and ALS genes

```{r ALSFTDgenes}
setwd("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/250325_NMDi")

## Crypticdfs
cryptic_df = read_delim("output_tables/250329_CrypticCoordinates_Vis.csv")
cryptic_df_high <- read_delim("output_tables/250409_CrypticCoordinates_HighExp.csv")

## Data
alsgenes = read_delim("data/250409_ALSgenes.csv")
alsgenes$gene[which(alsgenes$gene %in% cryptic_df$`Gene Symbol`)]
# Three cryptic exon genes directly related: ATXN1, CHMP2B, UNC13A

## Pathway analysis: Are any cryptic exon genes affiliated with the same pathways as highly associated genes?

# Add NCBI IDs
crypticgenes = cryptic_df$`Ensembl ID`
alsgenesEntrez = bitr(alsgenes$gene, 
                          fromType="SYMBOL", 
                          toType="ENTREZID", 
                          OrgDb="org.Hs.eg.db")

crypticgenesEntrez <- bitr(crypticgenes, 
                          fromType="ENSEMBL", 
                          toType="ENTREZID", 
                          OrgDb="org.Hs.eg.db")

crypticgenesEntrez <- left_join(crypticgenesEntrez, cryptic_df[,c(1,3)],
                                by=join_by("ENSEMBL"==`Ensembl ID`))


keggCE <- bitr_kegg(unique(c(crypticgenesEntrez$ENTREZID,alsgenesEntrez$ENTREZID)), 
                    fromType="ncbi-geneid", 
                    toType="kegg", 
                    organism="hsa")

crypticgenesEntrez <- left_join(crypticgenesEntrez,keggCE,by=join_by("ENTREZID"=="ncbi-geneid"))
alsgenesEntrez <- left_join(alsgenesEntrez,keggCE,by=join_by("ENTREZID"=="ncbi-geneid"))

# Manual fill
crypticgenesEntrez$kegg[which(crypticgenesEntrez$`Gene Symbol` == "CACNA1C")] = 4850
crypticgenesEntrez$kegg[which(crypticgenesEntrez$`Gene Symbol` == "FEZ1")] = 9638

## Enrichment analysis
genes = sort(unique(as.numeric(c(crypticgenesEntrez$kegg,alsgenesEntrez$kegg))),
             decreasing = T)

kk <- enrichKEGG(gene = genes,organism = 'hsa',pvalueCutoff = 1)
# saveRDS(kk, file = "data/250410_outputKeggOverlap.RDS")

# Find pathways with genes from both CE genes and ALS genes
keggRes <- kk@result 
genesAll <- data.frame(nGene=t(data.frame(lapply(kk@geneSets,length)))) %>%
  rownames_to_column("id")
keggRes <- left_join(keggRes,genesAll, by=join_by("ID" == "id")) %>% filter(Count > 1)
keggResGenes <- strsplit(keggRes$geneID,"/")

overlapALSce <- c()
for(i in 1:length(keggResGenes)){
  if(length(which(crypticgenesEntrez$kegg %in% unlist(keggResGenes[i]))) != 0){
    if(length(which(alsgenesEntrez$kegg %in% unlist(keggResGenes[i])))){
      overlapALSce <- append(overlapALSce,i)
    }
  }
  rm(i)
}

keggRes <- keggRes[overlapALSce,] %>% arrange(-Count)
#write.csv(keggRes,"output_tables/250410_PathwayOverlap.csv")

# Re-ID genes
crypticgenesEntrez <- crypticgenesEntrez %>% unique()
alsgenesEntrez <- alsgenesEntrez %>% unique()

keggResAnalysis <- keggRes %>% dplyr::select(category, subcategory, ID, 
                                             Description, geneID, 
                                             Count, nGene) %>%
  mutate(genesALS=NA,genesCE=NA)

for(i in 1:nrow(keggResAnalysis)){
  genes <- unlist(strsplit(keggRes$geneID[i],"/"))
  genesALS <- alsgenesEntrez$SYMBOL[which(alsgenesEntrez$kegg %in% genes)]
  genesCE <- crypticgenesEntrez$`Gene Symbol`[which(crypticgenesEntrez$kegg %in% genes)]
  
  keggResAnalysis$genesALS[i] = paste0(genesALS, collapse = ", ")
  keggResAnalysis$genesCE[i] = paste0(genesCE, collapse = ", ")
  rm(genes, genesALS, genesCE, i)
}

keggResAnalysis$nCE = unlist(lapply(keggResAnalysis$genesCE,
                                    function(x) length(unlist(strsplit(x,", ")))))
keggResAnalysis$nALS = unlist(lapply(keggResAnalysis$genesALS,
                                     function(x) length(unlist(strsplit(x,", ")))))

keggResAnalysis <- keggResAnalysis %>% relocate(ID, .before = "category")

#write.csv(keggResAnalysis,"output_tables/250410_PathwayOverlap_IDed.csv")

keggResAnalysis <- keggResAnalysis %>% filter(!(subcategory %in% c("Neurodegenerative disease",
                                                               "Infectious disease: bacterial",
                                                               "Infectious disease: viral",
                                                               "Cancer: overview")))
#write.csv(keggResAnalysis,"output_tables/250410_PathwayOverlap_IDed_filtered.csv")

keggResAnalysis %>% 
  mutate(Description = factor(Description, 
                              c(rev((keggResAnalysis %>% arrange(-Count))$Description)))) %>%
  top_n(20,wt=nCE) %>%
  pivot_longer(cols=10:11, names_to = "typeCount", values_to = "countGenes") %>%
  mutate(typeCount = factor(typeCount, c("nCE","nALS"))) %>%
  ggplot(aes(x =countGenes ,y=Description, fill=typeCount)) +geom_col()+
  theme_classic()+ylab("")+xlab("# of Genes")+
  scale_fill_manual(values = c("#D1D1D1","#262626"))+
  scale_x_continuous(expand = c(0, 0),limits = c(0,12))+
  theme(text = element_text(color="black", family="Helvetica", size =10))
ggsave("output_fig/250410_ALS_CE_genePathways.png",device = "png", 
       width = 40, height = 25, units = "cm",limitsize = FALSE)

```

