---
title: "250410_GEX"
author: "Irika Sinha"
date: "2025-04-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The purpose of this script is to take the file with manually identified cryptic exon coordinates and use those coordinates to identify left and right junction PSIs in the different conditions for i3N. 

## Packages

```{r packages}
CRANpackages <- c("tidyverse", "ggplot2", "ggpubr", "ggstats","BiocManager","viridis","gghighlight", "ggrepel")
biocPackages <- c("apeglm", "DESeq2")

for(i in CRANpackages){
  if(!(i %in% rownames(installed.packages()))){
    install.packages(pkgs = i)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

for(i in biocPackages){
  if(!(i %in% rownames(installed.packages()))){
    BiocManager::install(pkgs = i, ask = F)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

rm(CRANpackages,biocPackages)

```

## DEG analysis
Nextflow RNA-seq pipeline used to generate DESeq2 objects.
Used DESeq2 vignette to write analysis script: https://www.bioconductor.org/packages/devel/bioc/vignettes/DESeq2/inst/doc/DESeq2.html

```{r DESeq2}
setwd("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/NMDi_TDP43kd_repo/")
# Load data
load("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/data/nmdi_all_deseq2.dds.RData")
cryptic_df = read_delim("data/250601_CE_table.csv")

# Add metadata
colnames(dds@colData)[which(colnames(dds@colData) == "Group1")] = "Treatment"
colnames(dds@colData)[which(colnames(dds@colData) == "Group2")] = "Rep"
dds@colData$NMDi = as.factor(c(rep("WT",2),rep("KD",8),rep("WT",4),rep("KD",8)))
dds@colData$NMDi = factor(dds@colData$NMDi, levels =c("WT","KD"))
dds@colData$tdp = as.factor(c(rep("WT",12),rep("KD",10)))
dds@colData$tdp = factor(dds@colData$tdp, levels =c("WT","KD"))
dds@colData$seqDate = as.factor(c(rep("batch1",10),rep("batch2",12)))
design(dds) <- ~ tdp + NMDi + seqDate

# saveRDS(dds, "data/nmdi_all_annotated_deseq2.dds.RDS")

## Subset to samples of interest
## Pre-filtering - there are 4 samples
dds <- dds[,11:14]
dds <- dds[rowSums(counts(dds)) >= 10,] # at least 10 total reads across all samples
dds_counts <- data.frame(dds@assays@data@listData$counts) # Extract counts for later

## DESeq2 Analysis
# Add experiment design
# LFC shrinkage for vis + Extract results
dds$tdp <- factor(dds$tdp, levels = c("WT","KD"))
design(dds) <- ~ tdp
dds <- DESeq(dds)
# res <- results(dds, contrast=c("tdp","KD","WT"))
res <- lfcShrink(dds, coef="tdp_KD_vs_WT", type="apeglm")

# Create dataframe with logFC and p.adj values for each gene. Add empty cols for CE type, CE name, TDPCE (1-PSI)
res_df <- data.frame(res) %>% filter(!is.na(log2FoldChange)) %>% 
  mutate(neglog10p = -log10(padj), gene_type=NA, gene_name=NA, ce_psi=NA)

## Populate results df using CE information
for(i in 1:nrow(cryptic_df)){
  n = which(rownames(res_df) == cryptic_df$`Ensembl ID`[i]) # Identify row in results
  res_df$gene_type[n] = tolower(cryptic_df$type[i])
  res_df$gene_name[n] = cryptic_df$`Gene Symbol`[i]
  res_df$ce_psi[n] = (cryptic_df$avgT[i])/100
  
  rm(i,n)
}

# Plot log2FC vs -log10Padj with CEs with abs(lfc) > 1 and p.adj < 10^-20 named on plot
res_df %>% mutate(neglog10p = ifelse(is.infinite(neglog10p), 50, neglog10p),
                  neglog10p = ifelse(neglog10p > 50, 50, neglog10p),
                  log2FoldChange = ifelse(log2FoldChange < -5,-5, 
                                          ifelse(log2FoldChange > 5, 5, log2FoldChange)),
                  gene_name = ifelse(neglog10p>20 & abs(log2FoldChange) > 1,gene_name,"")) %>%
  ggplot(aes(x=log2FoldChange,y=neglog10p, color=factor(gene_type)))+ 
  geom_point(alpha=0.8,size=3) + theme_classic() + 
  gghighlight(!is.na(gene_type),unhighlighted_params = list(alpha=0.5, size=2))+
  geom_label_repel(aes(label = gene_name), 
                   box.padding = 0.5, max.overlaps = Inf,fontface = "bold",
                   fill = alpha(c("white"),0.8), label.size = NA)+
  scale_color_manual(values=c("#002D72","#69140E","#ffc000","#82735C"))+
  theme(text = element_text(family="Helvetica"))+
  ylim(0,60)
# ggsave("output_fig/250413_Ctrl_TDPkd_GEx.png",device = "png", 
#        width = 50, height = 30, units = "cm",limitsize = FALSE)

## Create new dds object for CE-adjusted p-vales
adj_count <- dds_counts
cryptic_df_PSImax <- cryptic_df[,-c(7:8,10:41)] %>% 
  group_by(`Gene Symbol`, `Ensembl ID`) %>% 
  summarize(avgT = max(avgT)) %>% # For gene with multiple CEs, choose higher PSI
  left_join(cryptic_df %>% dplyr::select(`Gene Symbol`,type,avgT,maxTDP), 
            by = c("Gene Symbol", "avgT")) %>%
  ungroup() %>%
  mutate(pct_transcript = 1, type = tolower(type)) %>%
  distinct()

# For each gene with a cryptic exon, change the TDPKD value to reflect effective downregulation of the gene due to CE inclusion
# Multiply raw_count value by (1-CE_PSI)
for(i in 1:nrow(cryptic_df_PSImax)){
  n = which(rownames(adj_count) == cryptic_df_PSImax$`Ensembl ID`[i]) # Identify row in counts for CE
  TDPKD_PSI = ifelse(!is.na(cryptic_df_PSImax$avgT[i]),cryptic_df_PSImax$avgT[i],0) # Extract TDP-43 KD only PSI
  pct_transcript = 1-TDPKD_PSI/100 # Calculate % functional
  cryptic_df_PSImax$pct_transcript[i] = pct_transcript
  
  # Adjust counts
  adj_count$TDPKD_1[n] = as.integer(round((adj_count$TDPKD_1[n])*pct_transcript,0))
  adj_count$TDPKD_2[n] = as.integer(round((adj_count$TDPKD_2[n])*pct_transcript,0))
  
  rm(i, n, TDPKD_PSI,pct_transcript)
}

## Create DESeq2 object and do analysis as before
# Extract results
dds_adj <- DESeqDataSetFromMatrix(countData = as.matrix(adj_count),
                              colData = dds@colData,
                              design = ~ tdp)

dds_adj <- DESeq(dds_adj)
res_adj <- lfcShrink(dds_adj, coef="tdp_KD_vs_WT", type="apeglm")
res_adj_df <- data.frame(res_adj) %>% filter(!is.na(log2FoldChange)) %>% 
  mutate(neglog10p = -log10(padj), gene_type=NA, gene_name=NA,
         TDP_only = NA, TDP_max = NA, dPSI = NA,
         gene_NMD = NA, dpct = NA, log2PSI = NA)

## Populate results df using CE information
for(i in 1:nrow(cryptic_df_PSImax)){
  n = which(rownames(res_adj_df) == cryptic_df_PSImax$`Ensembl ID`[i])
  res_adj_df$gene_type[n] = toupper(cryptic_df_PSImax$type[i])
  res_adj_df$gene_name[n] = cryptic_df_PSImax$`Gene Symbol`[i]
  res_adj_df$TDP_only[n] = cryptic_df_PSImax$avgT[i]
  res_adj_df$TDP_max[n] = cryptic_df_PSImax$maxTDP[i]
  res_adj_df$dPSI[n] = cryptic_df_PSImax$maxTDP[i] - cryptic_df_PSImax$avgT[i]
  res_adj_df$dpct[n] = (cryptic_df_PSImax$maxTDP[i] - cryptic_df_PSImax$avgT[i] + 0.01)/(cryptic_df_PSImax$avgT[i] + 0.01)
  res_adj_df$log2PSI[n] = log2((cryptic_df_PSImax$maxTDP[i] + 0.01)/(cryptic_df_PSImax$avgT[i] + 0.01))
  
  if(cryptic_df_PSImax$avgT[i] < 10 | is.na(cryptic_df_PSImax$avgT[i])){
    res_adj_df$gene_NMD[n]  = "10pct"
    if(cryptic_df_PSImax$avgT[i] < 5 | is.na(cryptic_df_PSImax$avgT[i])){
      res_adj_df$gene_NMD[n]  = "5pct"
      if(cryptic_df_PSImax$avgT[i] < 1 | is.na(cryptic_df_PSImax$avgT[i])){
        res_adj_df$gene_NMD[n]  = "1pct"
    }
    }
  }
  
  rm(i)
}

# Graph CE-adjusted log2FC and -log10p.adj
# CEs with (lfc) < -1 and p.adj < 10^-20 named on plot
# saveRDS(res_adj,"data/251214_resLFC_adj.RDS")
res_adj_df %>% mutate(neglog10p = ifelse(is.infinite(neglog10p), 50, neglog10p),
                  neglog10p = ifelse(neglog10p > 50, 50, neglog10p),
                  log2FoldChange = ifelse(log2FoldChange < -5,-5, 
                                          ifelse(log2FoldChange > 5, 5, log2FoldChange)),
                  gene_name = ifelse(padj>20 & log2FoldChange < -1,gene_name,"")) %>%
  ggplot(aes(x=log2FoldChange,y=neglog10p, color=factor(gene_type)))+ 
  geom_point(alpha=0.8,size=3) + theme_classic() + 
  gghighlight(!is.na(gene_type),unhighlighted_params = list(alpha=0.5, size=2))+
  geom_label_repel(aes(label = gene_name), 
                   box.padding = 0.5, max.overlaps = Inf,fontface = "bold",
                   fill = alpha(c("white"),0.8), label.size = NA)+
  scale_color_manual(values=c("#002D72","#69140E","#ffc000","#82735C"))+
  theme(text = element_text(family="Helvetica"))+
  ylim(0,60)
ggsave("output_fig/251215_Ctrl_TDPkd_GEx_adj.png",device = "png", 
       width = 50, height = 30, units = "cm",limitsize = FALSE)

# Graph CE-adjusted log2FC and -log10p.adj
# CEs with (lfc) < -1 and p.adj < 10^-20 named on plot
# saveRDS(res_adj,"data/251214_resLFC_adj.RDS")
res_adj_df %>% mutate(neglog10p = ifelse(is.infinite(neglog10p), 50, neglog10p),
                  neglog10p = ifelse(neglog10p > 50, 50, neglog10p),
                  log2FoldChange = ifelse(log2FoldChange < -5,-5, 
                                          ifelse(log2FoldChange > 5, 5, log2FoldChange)),
                  gene_name = ifelse(log2FoldChange < log2(0.8) & dPSI > 0.2 & !is.na(gene_NMD),gene_name,"")) %>%
  ggplot(aes(x=log2FoldChange,y=dPSI))+ 
  geom_point(aes(color=factor(gene_NMD)),alpha=0.8,size=3) + theme_classic() + 
  gghighlight(!is.na(gene_type),unhighlighted_params = list(alpha=0.5, size=2))+
  geom_label_repel(aes(label = gene_name), 
                   box.padding = 0.5, max.overlaps = Inf,fontface = "bold",
                   fill = alpha(c("white"),0.8), label.size = NA)+
  scale_color_manual(values=c("#002D72","#69140E","#ffc000","#82735C"))+
  theme(text = element_text(family="Helvetica"))+
  #geom_smooth(method=lm , color="red", se=FALSE)+
  stat_cor()+xlim(-5,2.3)

res_adj_df %>% mutate(neglog10p = ifelse(is.infinite(neglog10p), 50, neglog10p),
                  neglog10p = ifelse(neglog10p > 50, 50, neglog10p),
                  log2FoldChange = ifelse(log2FoldChange < -5,-5, 
                                          ifelse(log2FoldChange > 5, 5, log2FoldChange)),
                  gene_name = ifelse(log2FoldChange < log2(0.5) & log2PSI > log2(2),gene_name,""),
                  log2PSI = ifelse(log2PSI > 5,5,log2PSI)) %>%
  ggplot(aes(x=log2FoldChange,y=log2PSI))+ 
  geom_point(aes(color=factor(gene_NMD)),alpha=0.8,size=3) + theme_classic() + 
  # gghighlight(!is.na(gene_type),unhighlighted_params = list(alpha=0.5, size=2))+
  geom_label_repel(aes(label = gene_name), 
                   box.padding = 0.5, max.overlaps = Inf,fontface = "bold",
                   fill = alpha(c("white"),0.8), label.size = NA)+
  scale_color_manual(values=c("#002D72","#69140E","#ffc000","#82735C"))+
  theme(text = element_text(family="Helvetica"))+
  #geom_smooth(method=lm , color="red", se=FALSE)+
  stat_cor()+xlim(-5,2.3)+ylim(0,6)



```