---
title: "250506_YY_OE"
author: "Irika Sinha"
date: "2025-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The purpose of this script is to take the file output of CellProfiler and figure out which rescues worked

## Packages

```{r packages}
CRANpackages <- c("tidyverse", "ggplot2","gghighlight","ggpubr")

# CRANpackages <- c("tidyverse", "ggplot2", "ggpubr", "ggstats","BiocManager","viridis","gghighlight", "ggrepel")
biocPackages <- c()

for(i in CRANpackages){
  if(!(i %in% rownames(installed.packages()))){
    install.packages(pkgs = i)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

for(i in biocPackages){
  if(!(i %in% rownames(installed.packages()))){
    BiocManager::install(pkgs = i, ask = F)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

rm(CRANpackages,biocPackages)

```

## Data
```{r data}
setwd("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/250325_NMDi")
cryptic_df <- read_delim("data/250509_CE_table.csv")
scores_df <- read_delim("data/250509_IS_Rescue_YY_Quant_Pool.csv")

```

## Normalize scores to shCTR-GFP and shTDP43-GFP by batch
```{r norm}
# Determine survival per well (each n)
scores_df$survival = 1-as.numeric(scores_df$pctPI)
scores_df <- scores_df %>% group_by(Batch, OE, Rep) %>% summarize(survival = mean(survival))

# Normalize survival (pctPI-)
# 0 = shTDP43-GFP
# 1 = shCTR-GFP
# Note: batch 5 has no shCTR-GFP values. Avg from other batches used

batches = unique(scores_df$Batch)
scores_df$Norm = NA

for(i in batches){
  r = which(scores_df$Batch == i)
  df_temp <- scores_df[r,]
  
  maxSurv = which(df_temp$OE == "shCtrl")
  minSurv = which(df_temp$OE == "GFP")
  max = median(df_temp$survival[maxSurv])
  min = median(df_temp$survival[minSurv])
  
  scores_df$Norm[r] = round((scores_df$survival[r] - min)/(max-min),3)
  rm(r,maxSurv,minSurv,max,min,i, df_temp)
}

scores_df <- scores_df %>% filter(OE != "GRAMD1A\t\t")

df_summary <- scores_df %>% group_by(OE) %>% summarize(med = median(Norm)) %>% arrange(med)

```



## Visualize
```{r visual}
# generate colors
pal <- scales::gradient_n_pal(colours = c("#820000","white","#002D72"), values= c(-0.2, 0,0.2))
df_summary$fillColor <- pal(df_summary$med)
df_summary <- df_summary %>% 
  mutate(fillColor = ifelse(med <= -0.2, "#820000",
                            ifelse(med >= 0.2, "#002D72", fillColor)))
# df_summary$fillColor[which(df_summary$OE == "GFP")] = "#820000"
order = df_summary$OE

scores_df %>% mutate(OE = factor(OE, levels = order)) %>%
  ggplot(aes(x=OE,y=Norm, fill = OE)) +
  geom_jitter(alpha=0.5, width=0.2, size=3, color="black")+
  geom_boxplot(alpha=0.7, outliers = F) + 
  scale_fill_manual(values=df_summary$fillColor) +
  theme_classic()+ # scale_y_continuous(expand = c(0, 0),limits = c(-1.1,1.1))+
  theme(text = element_text(color="black", family = "Helvetica", size=15),
        axis.text.x = element_text(angle = 45, hjust=1), legend.position = "none")+
  xlab("")+ylab("Survival")+
  stat_compare_means(label = "p.signif", method = "wilcox.test", ref.group = "GFP")

ggsave("output_fig/250506_shRNA_toxicity.png",device = "png", 
       width = 50, height = 20, units = "cm",limitsize = FALSE)

# Calculate p-values of difference from control using Wilcox test - not normalized
df_stats <- compare_means(formula= Norm ~ gene, data=scores_df, ref.group = "GFP", method = "wilcox.test")


```


