---
title: "251113_CLIPseq"
author: "Irika Sinha"
date: "2025-11-13"
output: ''
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
CRANpackages <- c("tidyverse", "BiocManager", "ggrepel","viridis", "ggridges")
#biocPackages <- c("apeglm")

for(i in CRANpackages){
  if(!(i %in% rownames(installed.packages()))){
    install.packages(pkgs = i)
  } else{
    update.packages(i)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

# for(i in biocPackages){
#   if(!(i %in% rownames(installed.packages()))){
#     BiocManager::install(pkgs = i, ask = F)
#   } else{
#     BiocManager::install(pkgs = i, ask = F, update=T)
#   }
#   library(package = i, character.only = T, quietly = T)
#   rm(i)
# }

rm(CRANpackages)
# rm(biocPackages)

## List Package Versions
versions = installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
data.frame(versions)
rm(versions)

```

## CLIP-seq Analysis
See: 251104_eCLIP_fastq_dl
In summary:
-sra-tools used to download fasta files
-umi_tools used to extract UMIs
-Trim Galore! used to trim reads
-STAR used to align files to GRCh38 v115
-samtools used to index bam files
-iCount used to quantify Xlink sites, calculate significance, annotate sites, and generate summary statistics

```{r Data}
setwd("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/250325_NMDi")
## Load identified CEs & identify regions within 600 bp
ce_df <- read_csv("data/251114_CLIPCE_Search.csv") %>% 
  mutate(chr = str_split_i(`Cryptic Exon Location\n(hg38)`, ":",1),
         region = str_split_i(`Cryptic Exon Location\n(hg38)`, ":",2),
         start = str_split_i(region,"-",1),
         end = str_split_i(region,"-",2),
         testStart = as.numeric(start) - 600,
         testEnd = as.numeric(end) + 600) %>%
  dplyr::select(!region)

## Load CLIP data and filter to CE genes
data_files <- paste0("data/CLIP/",list.files("data/CLIP"))
data_files <- lapply(data_files, function(file) read_tsv(file) %>% 
                       mutate(fileName = str_split_i(str_split_i(file, "/", 3), "_", 1)) %>%
                       filter(group_id %in% ce_df$`Ensembl ID`)) 
meta <- read_csv("data/251028_eclip_info.csv")

## Merge CLIP peaks into a single df
df <- reduce(data_files, rbind) %>% 
  left_join(meta %>% dplyr::select(ENA_RUN, Notes),
            by = join_by(fileName == ENA_RUN))

## Subset CLIP data for every CE
df_relevant <- ce_df %>%
  dplyr::select(`Gene Symbol`,`CE Detail`,`Ensembl ID`,`ID #`,testStart,testEnd) %>% 
  rowwise() %>%
  mutate(peaks = list(df %>% 
                        filter(group_id == `Ensembl ID`,
                               position >= testStart,
                               position <= testEnd))) 

df_peaks <- reduce(df_relevant$peaks,rbind) %>% as.data.frame()
unique(ce_df$`Gene Symbol`[which(!(ce_df$`Ensembl ID`%in% df_peaks$group_id ))])

ggplot(df_peaks, aes(y = Notes, x = (as.numeric(FDR)), fill=Notes)) + 
  geom_density_ridges(alpha=0.8)+
  scale_fill_viridis(discrete=TRUE) +
  theme_classic()+scale_y_discrete(expand=c(0,0))

df_peaks %>% filter(FDR < 0.05) %>%
  ggplot(aes(x = score_extended, y =-log10(FDR+0.0001), fill = Notes))+
  geom_point(alpha=0.8, shape = 21, size = 3) + 
  theme_classic() 

df_peaks %>% filter(as.numeric(FDR) < 0.05) %>%
  ggplot(aes(x = name, y =-log10(FDR+0.0001))) +
  geom_boxplot() +
  theme_classic()


```





