---
title: "251124_SnapMine_MES"
author: "Irika Sinha"
date: "2025-11-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

The purpose of this script is use SnapMine to check PSIs of CEs in public RNA-Seq datasets

## Packages

SnapMine package is still in development but is functional. It can be downloaded from GitHub.

```{r packages, message = FALSE, warning = FALSE}
update.packages("BiocManager")
library("BiocManager")
packages <- c("tidyverse","ggplot2","data.table","biomaRt", "pheatmap","viridis", "progress")

for(i in packages){
  if(!(i %in% rownames(installed.packages()))){
    BiocManager::install(pkgs = i, ask = F)
  } else{
    BiocManager::install(pkgs = i, ask = F, update=T)
  }
  library(package = i, character.only = T, quietly = T)
  rm(i)
}

rm(packages)

## Install SnapMine package from GitHub
remotes::install_github("irikas/SnapMine_Paper", subdir = "snapmine")
library(snapmine)

## List Package Versions
versions = installed.packages()[names(sessionInfo()$otherPkgs), "Version"]
data.frame(versions)
rm(versions)

```

## Load files and run Snaptron query
Copied from introduction vignette!

```{r files, eval=T}
## Load df
df <- fread("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/NMDi_TDP43kd_repo/data/251126_CEdf.csv")

## Original df did not have strand info so need to use biomaRt
## Update df
mart <- useEnsembl(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
info <- getBM(attributes = c("ensembl_gene_id", "strand"), values = df$`Ensembl ID`, mart = mart)
df <- df %>%
  left_join(info, by = join_by(`Ensembl ID` == ensembl_gene_id)) %>%
  mutate(strand = ifelse(strand == 1, "+", "-"))
rm(mart, info)

## Create info_df file
info_df <- data.frame(
  novel_junc_id = paste(df$`Gene Symbol`, df$`ID #`, sep = "_"),
  compilation = "sra_human",
  strand = df$strand,
  novel_junc_left_coord = df$LeftJunction,
  novel_junc_right_coord = df$RightJunction,
  canon_junc_coord = df$`Canonical Splice Junction`
)
```

```{r query, eval = F}
## Run query
# Run twice for long and wide dfs.
# Could also run without flattening - this would lead to a list of dfs and then both flatten functions could be done manually using [flatten_counts]
result_df_long <- calcPSI_bulk(info_df, flatten_long = T)
result_df_wide <- calcPSI_bulk(info_df, flatten_wide = T)
# saveRDS(result_df_long, "/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/250325_NMDi/output_tables/251204_snapmine_results.RDS")
# saveRDS(result_df_wide, "/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/250325_NMDi/output_tables/251204_snapmine_result_df_wide.RDS")
```

```{r load_df, include = F}
result_df_long <- readRDS("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/output_tables/251204_snapmine_results.RDS")
result_df_wide <- readRDS("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/output_tables/251204_snapmine_result_df_wide.RDS")
```

## Visualize CE inclusion

```{r Visual}
result_df_wide[is.na(result_df_wide)] = 0

## Subset to samples with avgPSI > 15 for at least one CE
result_df_wide_subset <- result_df_wide %>% 
  mutate(maxPSI = apply(result_df_wide[, -1],
                        MARGIN = 1, function(x) max(x, na.rm = T))) %>%
  filter(maxPSI > 5) %>% dplyr::select(-maxPSI) 

## Subset to avgPSI > 5 for at least 10% tested CEs
result_df_wide_subset_overall <- result_df_wide_subset%>%
  mutate(n5 = apply(result_df_wide_subset[, -1],
                     MARGIN = 1,
                     function(x) length(which(x > 5)))) %>%
  filter(n5 > round(0.10 * nrow(info_df), 0)) %>%
  dplyr::select(-n5) %>%
  column_to_rownames(var = "sampleID")

m.results <- as.matrix(result_df_wide_subset_overall)
pheatmap(m.results, show_rownames = F, fontsize = 10,
         color = viridis(100,option="B"))

## Remove CEs with no values higher than 5%
colKeep <- apply(X = result_df_wide_subset_overall, MARGIN = 2, FUN = function(x) max(x) > 15)
result_df_wide_subset_overall_CEsubset <- result_df_wide_subset_overall[,colKeep]

pheatmap(as.matrix(result_df_wide_subset_overall_CEsubset), show_rownames = F, fontsize = 8,
        color = viridis(100,option="B"), legend_breaks = c(0,20,40,60,80,100))

# CE with medium-high inclusion
## Subset to avgPSI > 15 for at least 20
result_df_TDPneg <- result_df_wide_subset_overall%>%
  mutate(n5 = apply(result_df_wide_subset_overall,
                     MARGIN = 1,
                     function(x) length(which(x > 15)))) %>%
  filter(n5 > 20) %>%
  dplyr::select(-n5) 

colKeep <- apply(X = result_df_TDPneg, MARGIN = 2, FUN = function(x) max(x) > 50)
result_df_TDPneg <- result_df_TDPneg[,colKeep]
pheatmap(as.matrix(result_df_TDPneg), 
         #show_rownames = F, 
         fontsize = 8,
        color = viridis(100,option="B"), legend_breaks = c(0,20,40,60,80,100))


# Samples with high CE inclusion
## Subset to avgPSI > 20 for at least 42 targets
## Subset to CEs within those samples with a max inclusion greater than 50
result_df_TDPneg <- result_df_wide_subset_overall%>%
  mutate(n5 = apply(result_df_wide_subset_overall,
                     MARGIN = 1,
                     function(x) length(which(x > 15)))) %>%
  filter(n5 > 42) %>%
  dplyr::select(-n5) 

colKeep <- apply(X = result_df_TDPneg, MARGIN = 2, FUN = function(x) max(x) > 50)
result_df_TDPneg <- result_df_TDPneg[,colKeep]

samples <- data.frame(sampleID = rownames(result_df_TDPneg))
sampleMeta <- snapmine::add_SnaptronMeta(samples, compilation = "sra_human") %>%
  mutate(rail_id = as.character(rail_id))
samples <- samples %>% full_join(sampleMeta, by = join_by("sampleID" == "rail_id"))

#manual
rowAnn = data.frame(sampleID = samples$sampleID,
                    Condition = c(rep("HeLa SMG6/7KD UPF1 CLIP",2),
                                   rep("MDA-MB231 shTDP43/shSRSF3",2),
                                   "HeLa shUPF1",
                                   "hMN siTDP-43",
                                   rep("MRC-5 MERS-CoV",5))) %>%
  column_to_rownames("sampleID")


pheatmap(as.matrix(result_df_TDPneg), 
         show_rownames = T, 
         fontsize = 12,
         color = viridis(100,option="B"), legend_breaks = c(0,20,40,60,80,100),
         border_color = "white",
         annotation_row = rowAnn,
         annotation_colors = list(Condition = 
                                    c(`HeLa SMG6/7KD UPF1 CLIP` = "#788AA3",
                                      `MDA-MB231 shTDP43/shSRSF3` = "#C83E4D",
                                      `HeLa shUPF1` = "#FFCF99",
                                      `hMN siTDP-43` = "#C83E4D",
                                      `MRC-5 MERS-CoV` = "#302F4D")))

# Samples with high CE inclusion
## Subset to avgPSI > 5 for at least 25% targets
## Subset to CEs within those samples with a max inclusion greater than 15 for at least 25% of samples
result_df_TDPneg <- result_df_wide_subset_overall%>%
  mutate(n5 = apply(result_df_wide_subset_overall,
                     MARGIN = 1,
                     function(x) length(which(x > 5)))) %>%
  filter(n5 > (0.25*423)) %>%
  dplyr::select(-n5) 

colKeep <- (apply(result_df_TDPneg,
                     MARGIN = 2,
                     function(x) length(which(x > 15)))>(0.25*nrow(result_df_TDPneg)))

result_df_TDPneg <- result_df_TDPneg[,colKeep]

## Add CE values from i3N
ces_kept <- str_split_i(colnames(result_df_TDPneg),"_",2)
ces_kept <- data.frame(ID = ces_kept) %>%
  left_join(df %>% dplyr::select(`ID #`,avgPSI_sgTARDBP, `avgPSI_sgTARDBP_shXRN1/shUPF1`),
            by = join_by(ID == `ID #`))

result_df_TDPneg[8,] = ces_kept$avgPSI_sgTARDBP
rownames(result_df_TDPneg)[8] = "sgTDP-43"

result_df_TDPneg[9,] = ces_kept$`avgPSI_sgTARDBP_shXRN1/shUPF1`
rownames(result_df_TDPneg)[9] = "sgTDP-43 + shUPF1/shXRN1"

samples <- data.frame(sampleID = rownames(result_df_TDPneg)[-c(8:9)])
sampleMeta <- snapmine::add_SnaptronMeta(samples, compilation = "sra_human") %>%
  mutate(rail_id = as.character(rail_id))
samples <- samples %>% full_join(sampleMeta, by = join_by("sampleID" == "rail_id"))

#manual
rowAnn = data.frame(sampleID = c(samples$sampleID, "sgTDP-43","sgTDP-43 + shUPF1/shXRN1"),
                    Condition = c(rep("MDA-MB231 shTDP43",2),
                                  rep("hMN siTDP43",2),
                                  rep("MERS-CoV",3),
                                  rep("i3N",2))) %>%
  column_to_rownames("sampleID") 

pheatmap(as.matrix(result_df_TDPneg), 
         show_rownames = T, 
         fontsize = 12,
         color = viridis(100,option="B"), legend_breaks = c(0,20,40,60,80,100),
         border_color = "black",
         annotation_row = rowAnn,
         annotation_colors = list(Condition = 
                                    c(`MERS-CoV` = "#788AA3",
                                      `MDA-MB231 shTDP43` = "#FFCF99",
                                      `hMN siTDP43` = "#C83E4D",
                                      `i3N` = "#302F4D")))



```


## Compare PSIs of all targets to TDP-43 neg nuclei
```{r TDPneg}
df <- fread("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Scripts/NMDi_TDP43kd_repo/data/251126_CEdf.csv")
result_df_wide <- readRDS("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/output_tables/251204_snapmine_result_df_wide.RDS")

Lee_sampleID <- fread("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/data/SRP185789_Lee_SraRunTable.csv") %>%
  rename(sampleID = SnaptronID)
HeLa_sampleID <- fread("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/data/SRP_Hela.csv") %>%
  rename(sampleID = SampleID)
hMN_sampleID <- fread("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/data/SRP166282_Klim_SRARunTable.csv")
Patients_sampleID <- fread("/Users/irika/Library/CloudStorage/OneDrive-JohnsHopkins/WongLing/Projects/NMD/NotGitHub/data/SRP16744_andSHSY5Y.csv") %>%
  arrange(SampleTItle)
result_df_wide[is.na(result_df_wide)] = 0

result_df_wide <- result_df_wide %>% filter(sampleID %in% c(Lee_sampleID$sampleID, HeLa_sampleID$sampleID, hMN_sampleID$sampleID, Patients_sampleID$sampleID)) %>%
  column_to_rownames("sampleID")

## Add CE values from i3N
ces_kept <- str_split_i(colnames(result_df_wide),"_",2)
ces_kept <- data.frame(ID = ces_kept) %>%
  left_join(df %>% dplyr::select(`ID #`,avgPSI_sgTARDBP, `avgPSI_sgTARDBP_shXRN1/shUPF1`),
            by = join_by(ID == `ID #`))

result_df_wide[nrow(result_df_wide)+1,] = ces_kept$avgPSI_sgTARDBP
rownames(result_df_wide)[nrow(result_df_wide)] = "sgTDP-43"

result_df_wide[nrow(result_df_wide)+1,] = ces_kept$`avgPSI_sgTARDBP_shXRN1/shUPF1`
rownames(result_df_wide)[nrow(result_df_wide)] = "sgTDP-43 + shUPF1/shXRN1"
result_df_wide[result_df_wide >50] = 50

# Annotation
annotation <- data.frame(sampleID = c(Lee_sampleID$sampleID, HeLa_sampleID$sampleID, hMN_sampleID$sampleID, Patients_sampleID$sampleID, "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1"),
                         sampleType = c(Lee_sampleID$`genotype/variation`,HeLa_sampleID$SampleTitle, hMN_sampleID$sample_title, 
                                        str_split_i(Patients_sampleID$SampleTItle[1:44], " replicate",1), 
                                        Patients_sampleID$SampleTItle[45:54], "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1")) 
# TDP-43 kds have less extreme effects

# Lee dataset
pheatmap(as.matrix(result_df_wide[as.character(c(Lee_sampleID$sampleID, "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1")),]), 
         show_colnames = F, 
         fontsize = 12,
         color = viridis(100,option="B"), 
         legend_breaks = c(0,25,50),
         border_color = "white",
         annotation_row = annotation %>% filter(sampleID %in% c(Lee_sampleID$sampleID, "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1")) %>%
           column_to_rownames("sampleID"))

# Lee dataset only TDP-43 neg
Lee_results <- result_df_wide[as.character(c(Lee_sampleID$sampleID[1:7], "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1")),]
Lee_annotation <- data.frame(sampleID = c(Lee_sampleID$sampleID[1:7], "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1"),
                             sampleType = c(Lee_sampleID$diagnosis[1:7], "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1"),
                             gender = c(Lee_sampleID$gender[1:7], rep("male",2))) %>% 
  column_to_rownames("sampleID")

pheatmap(as.matrix(Lee_results), 
         show_colnames = F, 
         fontsize = 12,
         color = viridis(100,option="B"), 
         legend_breaks = c(0,25,50),
         border_color = "white",
         annotation_row = Lee_annotation)


# What are those weird ones in nuclei but not i3n? + much higher in TDPneg
plot_results <- result_df_wide[as.character(c("sgTDP-43", "sgTDP-43 + shUPF1/shXRN1", Lee_sampleID$sampleID)),]
plot_annotation <- data.frame(sampleID = c(Lee_sampleID$sampleID, "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1"),
                              TDP = c(Lee_sampleID$`genotype/variation`, "sgTDP-43", "sgTDP-43"),
                             sampleType = c(Lee_sampleID$diagnosis, "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1")) %>% 
  column_to_rownames("sampleID")

plotCEs <- which((apply(plot_results[3:9,], 2, median) - apply(plot_results[1,], 2, median) > 5) &
                   (apply(plot_results[3:9,], 2, median) - apply(plot_results[10:16,], 2, median) > 5))

### USE THIS PLOT
pheatmap(as.matrix(plot_results[,plotCEs]), 
         show_colnames = T, 
         cluster_rows = F,
         fontsize = 12,
         color = viridis(100,option="F"), 
         legend_breaks = c(0,25,50),
         border_color = "black",
         annotation_row = plot_annotation,
        display_numbers = F)

### Other patients?
plot_results <- result_df_wide[as.character(c("sgTDP-43", "sgTDP-43 + shUPF1/shXRN1", Patients_sampleID$sampleID[c(7:18,23:48)])),]
plot_annotation <- data.frame(sampleID = c(Patients_sampleID$sampleID[c(7:18,23:48)], "sgTDP-43", "sgTDP-43 + shUPF1/shXRN1"),
                              TDP = c(str_split_i(Patients_sampleID$SampleTItle[c(7:18,23:48)], " ",1), "sgTDP-43", "sgTDP-43")) %>% 
  column_to_rownames("sampleID")

plotCEs <-  which((apply(plot_results[15:40,], 2, max) - apply(plot_results[3:14,], 2, max) > 0) &
                  apply(plot_results[3:14,], 2, max) < 5 & apply(plot_results[15:40,], 2, max)>5)

plot_results[plot_results >20] = 20
pheatmap(as.matrix(plot_results[,plotCEs]), 
         show_colnames = T, 
         cluster_rows = F,
         fontsize = 12,
         color = viridis(100,option="F"), 
         legend_breaks = c(0,10,20),
         border_color = "black",
         annotation_row = plot_annotation,
        display_numbers = F)


```



